spring:
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3307/db?useSSL=false&allowPublicKeyRetrieval=true
      username: user
      password: 1234
      hikari:
        maximum-pool-size: 20
        minimum-idle: 5
        connection-timeout: 30000
    slave1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3308/db?useSSL=false&allowPublicKeyRetrieval=true
      username: user
      password: 1234
      hikari:
        maximum-pool-size: 20
        minimum-idle: 5
        connection-timeout: 30000
    slave2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3309/db?useSSL=false&allowPublicKeyRetrieval=true
      username: user
      password: 1234
      hikari:
        maximum-pool-size: 20
        minimum-idle: 5
        connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect