spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://localhost:3307/test?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      username: user
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
    slaves:
      slave1:
        name: slave-1
        jdbc-url: jdbc:mysql://localhost:3308/test?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
        username: user
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
      slave2:
        name: slave-2
        jdbc-url: jdbc:mysql://localhost:3309/test?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
        username: user
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true